### ISSUE TITLE
Commits not found

### ISSUE THREAD

**Issue by omairvaiyani** [getsentry/action-release#12]
Hi thanks for publishing this action, very handy! I'm getting the following error in one of my repositories (private).

```
usr/bin/docker run --name sentryintegrationssentrygithubactionreleaselatest_b8842c --label 87c201 --workdir /github/workspace --rm -e SENTRY_AUTH_TOKEN -e SENTRY_ORG -e SENTRY_PROJECT -e INPUT_ENVIRONMENT -e INPUT_SOURCEMAPS -e INPUT_VERSION -e INPUT_FINALIZE -e INPUT_STARTED_AT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/redacted/redacted":"/github/workspace" sentryintegrations/sentry-github-action-release:latest
##[error]Command failed: /action-release/dist/sentry-cli releases set-commits 3.57.0 --auto
error: No commits found. Leaving release alone.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

Here is the simplified yaml:

```yml
name: Tag release

on:
  push:
    branches: [master]
    tags:
      - '!v*'

jobs:
  tag_release:
    name: Tag release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
         uses: getsentry/action-release@v1.0.0
         env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: REDACTED
          SENTRY_PROJECT: REDACTED
        with:
          environment: production    
          sourcemaps: '${{ env.GITHUB_WORKSPACE }}/app'
          version: 3.57.0
```

**Comment by jonesphillip** [comment]
@omairvaiyani do you have the GitHub integration installed with your repository configured on Sentry?

1. In Sentry, go to Settings > Integrations > GitHub
2. Go to the "Configurations" tab and click "Configure"
3. Confirm that your repository is there, if not click "Add Repository"

Let me know if that works for you!

**Comment by ivmakk** [comment]
@jonesphillip Thanks for the advice, it works like a charm! But better to post it the solution into README (Prerequisites or Troubleshooting section), because the repo integration step isn't obvious (release tracking via CLI reachable without direct integration with a repo).

**Comment by cainlevy** [comment]
Can confirm that this is a stumbling block. I would presume that a setting like "auto" would not error on a pre-condition like this.

**Comment by samwho** [comment]
I have also just stumbled on this as a problem. I didn't realise the GitHub integration needed to be added to Sentry before setting this up.

**Comment by DavidReinberger** [comment]
Me neither, however is there a possibility of a workaround? I'm working in an agency environment where we have all our repositories in our GitHub org and adding the Integration to our sentry instance would mean that others might not be able to do it right? 🤔
