### ISSUE TITLE
Cannot pull docker image in Github Action

### ISSUE THREAD

**Issue by grzegorzkrukowski** [getsentry/action-release#135]
# Github Sentry Action Release Bug Report

## Environment
ubuntu-latest runner on GitHub

How do you use this action?
```
- name: Create Sentry Release
   uses: getsentry/action-release@v1
```

Which version of the action?
v1

## Steps to Reproduce
We tried to re-run it a few times, but it keeps failing at a download step.
<img width="1339" alt="CleanShot 2023-03-15 at 15 24 42@2x" src="https://user-images.githubusercontent.com/1301068/225339160-e3f127d0-a4b7-4840-8242-231fe2579a28.png">

**Comment by LTKort** [comment]
It looks like it is a GitHub Packages problem; [https://githubstatus.com](https://t.co/HtwsytYFzd)

**Comment by stefvanesch** [comment]
Seems to be working again.

**Comment by grzegorzkrukowski** [comment]
> It looks like it is a GitHub Packages problem; [https://githubstatus.com](https://t.co/HtwsytYFzd)

Indeed, the incident appeared few hours after this happened, so it took them a while to announce it :)

**Comment by armenzg** [comment]
Thank you all for reporting and confirming the source of the problem!
