### ISSUE TITLE
GHA actions are uploading source maps with dist="null" (string)

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/action-release#140]
The [recent change](https://github.com/getsentry/action-release/pull/125) to support setting distribution (dist) in GHA actions introduced a couple of issues:

- If the set value is null, the file will be uploaded with the string "null" as distribution, and if an event does not have a distribution set the source map processing that relies on perfect matching release+dist will not work. 

- as reported in https://github.com/getsentry/action-release/issues/138, setting distribution is now required when uploading source maps. This is an optional value and should not be marked as required.

**Comment by florian-heer** [comment]
Warning from #141 still pops up : /

**Comment by florian-heer** [comment]
I'm sorry @armenzg ! I deployed the wrong version of my project which still used v1.3.1

I now can confirm that the warning from #141 is gone!

Thank you : )

**Comment by MaximeLaurenty** [comment]
I confirm:
- there is no more warning for me as well
- without providing `dist`, the action works and it is set to none (not null).
I couldn't test whether the source map processing work without dist yet, but I imagine it does given it used to when it was none with the CLI.
Thanks!

**Comment by armenzg** [comment]
@florian-heer @MaximeLaurenty thank you for confirming!
