### ISSUE TITLE
Warning when using "dist" as parameter

### ISSUE THREAD

**Issue by florian-heer** [getsentry/action-release#141]
# Github Sentry Action Release Bug Report

## Environment
Standard Github runners

Which version of the action?
v1.3.1

## Steps to Reproduce

As mentioned in the docs, the "dist" parameter is "Required when uploading sourcemaps."
If i add the "dist" parameter to the with section ill get a warning

Output of the action:
> Run getsentry/action-release@v1.3.1
  with:
    ignore_missing: true
    ignore_empty: true
    version: 1.22.18
    sourcemaps: build/static/js
    url_prefix: ~/static/js
    dist: c2ce317bc793b8f8f49f6b902de47eb85ca86245141
    finalize: true
  env:
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    SENTRY_AUTH_TOKEN: ***
    SENTRY_ORG: ***
    SENTRY_PROJECT: ***

## Actual Result

![Screenshot 2023-04-16 at 09 33 22](https://user-images.githubusercontent.com/28616513/232280775-81e8f821-c7be-42a3-ba93-7599313662a9.png)

**Comment by armenzg** [comment]
Thank you for reporting. I will fix it in #140
