### ISSUE TITLE
Upload artifact bundles instead of release bundles

### ISSUE THREAD

**Issue by jbergstroem** [getsentry/action-release#159]
According to the Sentry documentation, release bundles are deprecated in favor of [artifact bundles](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/). The github action should help its users to switch.

**Comment by landsman** [comment]
yeah

**Comment by smeubank** [comment]
https://github.com/getsentry/action-release/issues/206

there were multiple issues around this topic, so i created the following to track all of them centrally
