### ISSUE TITLE
"Action not found" with @v1 tag

### ISSUE THREAD

**Issue by ahecht** [getsentry/action-release#16]
The documentation and examples all have this line in the workflow:
```yml
uses: getsentry/action-release@v1
```

Using this generates the following error for me every time:
`An action could not be found at the URI 'https://api.github.com/repos/getsentry/action-release/tarball/v1'`

Changing it to `@master` or `@e36b15df9c918bb4f976e36893d08d35538daa59` (or some other specific commit) works, but I can't get it to work using the syntax from the documentation.

**Comment by mgaeta** [comment]
Thanks for catching this, I didn't realize GitHub didn't automatically generate major version tags. I just pushed `v1` and `v1.0`.
