### ISSUE TITLE
Option to inject source maps as well as upload

### ISSUE THREAD

**Issue by jjgriff93** [getsentry/action-release#165]
Looking at the code, it doesn't seem that this action performs a `sentry-cli inject` before uploading the source maps - so they aren't linked to my issues. It would be great if by default it did this so I don't need to add another step to call the Sentry CLI in my pipeline, with the option to disable if necessary.

**Comment by imolorhe** [comment]
Any chance someone can look into this? I was assuming this was a one-stop github action for sentry release especially since it has an option for sourcemaps but it doesn't inject the debug IDs (which is also not immediately obvious) so an additional step is stil needed.

**Comment by decline** [comment]
I also just experienced this issue 😕 Will have to go back to installing sentry-cli to have proper sourcemaps support...

**Comment by maximemalou** [comment]
Up here, would be great to have this option set up !

**Comment by smeubank** [comment]
opened an issue to track adding this functionality, will close this ticket to track there as a i want to link to any other issues which may come up and are also related in one place

https://github.com/getsentry/action-release/issues/206
