### ISSUE TITLE
Connecting to on-premise 

### ISSUE THREAD

**Issue by mennorenkens** [getsentry/action-release#17]
It's unclear to me if it is possible to connect this workflow to a on-premise version of Sentry or not. 
If so, how/where do I declare the URL?
Thanks!

**Comment by morganney** [comment]
You add [`SENTRY_URL`](https://docs.sentry.io/cli/configuration/#configuration-values) to the other environment variables and it will be picked up by the Sentry CLI.

**Comment by billyvg** [comment]
Answered via @morganney (thanks!)
