### ISSUE TITLE
Error during execution: repository path '/github/workspace/' is not owned by current user

### ISSUE THREAD

**Issue by noah-prosperops** [getsentry/action-release#182]
# Github Sentry Action Release Bug Report

## Environment

We're seeing this occur in our self-hosted runner shortly after the latest release.

```
Error: Command failed: /action-release/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases set-commits xxxxxx --auto
error: repository path '/github/workspace/' is not owned by current user; class=Config (7); code=Owner (-36)
```

How do you use this action?

Self-hosted runner on Ubuntu 22.04

Which version of the action?

v1

## Steps to Reproduce

Run workflow, observe error while executing `getsentry/action-release@v1`

## Expected Result

No error. This worked an hour ago.

## Actual Result

See error above

**Comment by rathpc** [comment]
I am also now seeing this issue and it is a major blocking problem as our org defines which versions of actions are allowed and this had been defined as v1 and not v1.4.1 which would have prevented this breaking version (1.5.0) from automatically being used. Can this be fixed ASAP or in the interim publish a revert until the cause is determined so that it will unblock workflows that target v1 as the version?

**Comment by rathpc** [comment]
Cc @scefali for visibility

**Comment by scefali** [comment]
Yea, let me revert.

**Comment by rathpc** [comment]
> Yea, let me revert.

Thank you!

**Comment by rathpc** [comment]
Yea it looks like this https://github.com/getsentry/action-release/pkgs/container/action-release-image/155367620?tag=latest is still what gets pulled

**Comment by alfieyfc** [comment]
We're also still experiencing the same issue at the moment 🙏

**Comment by scefali** [comment]
Damn, I guess deleting the release in GH and setting 1.4.1 the latest didn't work.
Hopefully rolling forward with a new version works: https://github.com/getsentry/action-release/releases/tag/v1.6.0

**Comment by rathpc** [comment]
That fixed it, thank you very much for the quick fix!

**Comment by alfieyfc** [comment]
Confirmed working from our end as well. Thanks!

**Comment by scefali** [comment]
Ok cl
