### ISSUE TITLE
Make 'environment' optional

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/action-release#19]
I was hoping to use this to push new releases mainly for suspected commits.
Once I make a build, I'll be promoting the same artifacts throughout different environments (stg/prod).

The docs state the environment, why is that the case? And would it be possible to make it optional?

**Comment by jbowen7** [comment]
I'm wondering the same. 
I've been successfully using `sentry-cli` to create new releases without ever specifying an environment.

**Comment by scefali** [comment]
Closing because this is now fixed
