### ISSUE TITLE
Error in creating the sentry release using GitHub Actions

### ISSUE THREAD

**Issue by r-aju** [getsentry/action-release#195]
# Github Sentry Action Release Bug Report

## Environment

How do you use this action?
 self-hosted runners (linux x86 arch)
Which version of the action?
getsentry/action-release@v1

## Steps to Reproduce

1. What
GitHub Actions file:
```
name: Sentry release

on:
  push:
    branches:
      - "github-action-test"

jobs:
  arm-build:
    runs-on: [arc-runner-kubernetes-ci]
    container:
      image: ubuntu:20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.1
          
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: "<TOKEN>"
          SENTRY_ORG: "<ORG>"
          SENTRY_PROJECT: "<NAME>"
          # SENTRY_URL: https://sentry.io/
        with:
          environment: stage     
          set_commits: skip
```

## Expected Result
Sentry creating a release version

What you thought would happen.

## Actual Result
The step failing with the below error
What actually happened. Maybe a screenshot/recording? Maybe some logs?
```
Error: Command failed: /action-release/node_modules/@sentry/cli-linux-x64/bin/sentry-cli releases propose-version
error: Could not automatically determine release name:
	 could not find repository at '.'; class=Repository (6); code=NotFound (-3) 

Please ensure your version control system is configured correctly, or provide a release name manually.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Comment by r-aju** [comment]
<img width="1165" alt="Screenshot 2024-06-14 at 5 21 01 PM" src="https://github.com/getsentry/action-release/assets/43216503/65be5f76-d5b5-459b-9837-29593587a8da">

**Comment by RSickenberg** [comment]
Read the doc: https://github.com/marketplace/actions/sentry-release

**Comment by smeubank** [comment]
in your example config i see:

> uses: getsentry/action-release@v1

please use v3, as stated in the docs linked [here](https://github.com/marketplace/actions/sentry-release)

> When adding the action, make sure to first checkout your repo with actions/checkout@v3. Otherwise it could fail at the propose-version step with the message:
