### ISSUE TITLE
Ensure this action is up-to-date and works with Debug IDs

### ISSUE THREAD

**Issue by mydea** [getsentry/action-release#200]
We should give this action a deeper look and ensure it works as expected. Especially, this includes ensuring that this works with Debug IDs.

**Comment by smeubank** [comment]
https://github.com/getsentry/action-release/issues/206

i just realized the issue i wrote is a duplicate. Out of selfishness, and because I already have been linking it other issues to inform users 😅  i will close this issue instead. 

But i recognize @mydea was here first! :D
