### ISSUE TITLE
Can't pass `url-prefix` for uploading sourcemaps

### ISSUE THREAD

**Issue by geoffharcourt** [getsentry/action-release#31]
Hi! 

We currently upload our sourcemaps in a post-deploy CLI task, but need the `url-prefix` option to get our sourcemaps pointing at the proper location. It looks like it would require passing in `url-prefix` as an option here: https://github.com/getsentry/action-release/blob/master/src/main.ts#L29

**Comment by scefali** [comment]
@geoffharcourt good feedback, I had a similar experience trying to get source maps to working. We'll get on this soon.

**Comment by scefali** [comment]
Resolved in v1.1.3

**Comment by geoffharcourt** [comment]
Thanks @scefali!
