### ISSUE TITLE
Allow Sourcemaps to be a array

### ISSUE THREAD

**Issue by amcdnl** [getsentry/action-release#43]
It would be better if the source maps option would accept an array. Instead of:

```
sourcemaps: ./dist/bar ./out/bar
```

it would be:

```
sourcemaps:
  - ./dist/bar
  - ./out/bar
```

**Comment by mgaeta** [comment]
According to the docs, [`jobs.<job_id>.steps[*].with`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith) must be a `map` of string keys to string values. We'll be able to do this when GitHub Actions implement array parameters.

**Comment by amcdnl** [comment]
What about glob support? I think that would clean this up even more for me.
