### ISSUE TITLE
Upgrade to latest CLI

### ISSUE THREAD

**Issue by XVincentX** [getsentry/action-release#59]
It seems like the CLI in the Sentry Action release is stuck to 1.59, while 1.65 supports the `ignore missing` commit flag.

**Comment by XVincentX** [comment]
Thanks people! Is there any chance you folks could also to a new Action Release so we can incorporate it in our workflows?

**Comment by kamilogorek** [comment]
We'll release a new version soon. People from US have to wake up first :)

**Comment by XVincentX** [comment]
Fantastic. I just woke up as well ;)

Thank you very much for the prompt response!

**Comment by kamilogorek** [comment]
Done
