### ISSUE TITLE
Doesn't seem to like releases based on tags

### ISSUE THREAD

**Issue by cesarvarela** [getsentry/action-release#68]
### Environment

How do you use Sentry?
Sentry SaaS

You can check the project and the error here:
https://github.com/cesarvarela/stahp/runs/3249265240?check_suite_focus=true

**Comment by itssimon** [comment]
Yup, I can confirm the exact same thing is happening for us in a private repo.

**Comment by cwilby** [comment]
Similar issue - we use tags to mark releases, and release to Sentry based on those tags.

This issue is what I see: https://github.com/getsentry/action-release/issues/55

**Comment by smeubank** [comment]
unfortunately that link is now dead, closing unless someone can provide a reporduction and more information

![Image](https://github.com/user-attachments/assets/7e575df2-180a-4dd3-afb5-a0daa4a7fd86)
