### ISSUE TITLE
Action fails with ARM architecture

### ISSUE THREAD

**Issue by lbajsarowicz** [getsentry/action-release#81]
### Environment
1. Self-hosted Github Runner on ARM64 architecture

### Steps to Reproduce
1. Add the action to workflow

### Expected Result
1. Workflow executes successfully

### Actual Result
![image](https://user-images.githubusercontent.com/1639941/159603406-c96ea4b3-a58f-4320-a136-051db57e8b90.png)

**Comment by armenzg** [comment]
Hello @lbajsarowicz My apologies on the delay to respond. I just joined the team and we were transitioning on managing this repo.

As an alternative, you may use the `sentry-cli` directly:
https://docs.sentry.io/product/releases/setup/#notify-sentry
Here's a code snippet that may be close to what you need:
```
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits $SENTRY_RELEASE --auto
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps path-to-sourcemaps-if-applicable
          sentry-cli releases finalize $SENTRY_RELEASE
          sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
```

For anyone intending to work on this. I wrote a GH job that cross-compiles to the `arm64` architecture that could be the basis for supporting this:
https://github.com/getsentry/snuba/blob/94682dc0d1e3dd4043140bbc36d9d76a7f545d74/.github/workflows/ci.yml#L134-L192

**Comment by bbednarek** [comment]
@armenzg we are facing the same issue after migration to ARM architecture. When are you planning to support `ARM64` architecture?

**Comment by armenzg** [comment]
> @armenzg we are facing the same issue after migration to ARM architecture. When are you planning to support `ARM64` architecture?

Hi @bbednarek I'm pushing for it. No news at the moment. Using the CLI directly will help you work around this.

**Comment by bbednarek** [comment]
We moved to Sentry CLI, however it would be great to use official action instead.

Do you have any updates on this? When do you plan to support ARM architecture?

**Comment by armenzg** [comment]
Hi @bbednarek 
Sadly, this is not in the plans.

I'm asking around as it's been a while since I moved on from this project a long time ago.

**Comment by mmospanenko** [comment]
ARM is almost main arch today, all our runners on ARM instances... and will be great to get this runner working

**Comment by bittercoder** [comment]
Just wanted to add my 2 cents that this is really frustrating for our organisation as well - for anyone running github actions self-hosted cost management becomes important, and one of the ways to address that is running arm64 hosts.  This works great for _everything_ we use in terms of github actions except for sentry which isn't supporting arm64.  It doesn't feel like it would take much work to update the current build to target pushing linux/amd64 and  linux/arm64 images.

**Comment by mmospanenko** [comment]
yes, @bittercoder, we're having the same pain... only one x86 server (from ~100) in infrastructure and only for Sentry :)

**Comment by oxc** [comment]
Now that [GitHub supports github-hosted ARM64 runners](https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/) out of the box, more people will stumble over this. Like me 😢

**Comment by noamcohen97** [comment]
Until a fix is released, I built the exact same Docker image for ARM64, then created a local version of the action in .github/actions/sentry-action-release-arm64 with the new image. Apart from having to manually maintain the image, this is working fine for me.

**Comment by bbednarek** [comment]
@noamcohen97 Can you contribute to this repo and add ARM support?

**Comment by noamcohen97** [comment]
A multi-arch build is available at my fork: https://github.com/noamcohen97/sentry-action-release
Also - created #197 to handle this for future releases

**Comment by noamcohen97** [comment]
The latest images can now be found in the upstream container registry 🥳 
https://github.com/getsentry/action-release/pkgs/container/action-release-image/238133662?tag=latest

**Comment by armenzg** [comment]
Hello folks,
@noamcohen97 contributed a PR for this. Thank you, thank you!!!

Could you all please verify if it's working properly?
Also, please let me know if I need to cut a release or not. I have not looked into this for a very long time.

My apologies on the delay and I hope this works!

**Comment by noamcohen97** [comment]
I don't think a new release is a must. All version uses the latest tag which was just updated.

**Comment by damusnet** [comment]
datapoint here to say that it works, thank you :)
